name: build-dist 
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-dist:
    runs-on: rust:latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo install trunk
      - run: trunk build
